<?php

namespace ContainerVFFsevy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WD3zZRLService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wD3zZRL' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\CategoryController::index' => ['privates', '.service_locator.JuymgO0.App\\Controller\\CategoryController::index()', 'getCategoryControllerindexService', true],
            'App\\Controller\\CategoryController::new' => ['privates', '.service_locator.3BoFVFw.App\\Controller\\CategoryController::new()', 'getCategoryControllernewService', true],
            'App\\Controller\\PostController::index' => ['privates', '.service_locator._WkUlH_.App\\Controller\\PostController::index()', 'getPostControllerindexService', true],
            'App\\Controller\\PostController::new' => ['privates', '.service_locator.3BoFVFw.App\\Controller\\PostController::new()', 'getPostControllernewService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\CategoryController:index' => ['privates', '.service_locator.JuymgO0.App\\Controller\\CategoryController::index()', 'getCategoryControllerindexService', true],
            'App\\Controller\\CategoryController:new' => ['privates', '.service_locator.3BoFVFw.App\\Controller\\CategoryController::new()', 'getCategoryControllernewService', true],
            'App\\Controller\\PostController:index' => ['privates', '.service_locator._WkUlH_.App\\Controller\\PostController::index()', 'getPostControllerindexService', true],
            'App\\Controller\\PostController:new' => ['privates', '.service_locator.3BoFVFw.App\\Controller\\PostController::new()', 'getPostControllernewService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\CategoryController::index' => '?',
            'App\\Controller\\CategoryController::new' => '?',
            'App\\Controller\\PostController::index' => '?',
            'App\\Controller\\PostController::new' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\CategoryController:index' => '?',
            'App\\Controller\\CategoryController:new' => '?',
            'App\\Controller\\PostController:index' => '?',
            'App\\Controller\\PostController:new' => '?',
        ]);

        if (isset($container->privates['.service_locator.wD3zZRL'])) {
            return $container->privates['.service_locator.wD3zZRL'];
        }

        return $container->privates['.service_locator.wD3zZRL'] = $instance;
    }
}
