<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVFFsevy\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVFFsevy/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVFFsevy.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVFFsevy\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVFFsevy\App_KernelDevDebugContainer([
    'container.build_hash' => 'VFFsevy',
    'container.build_id' => '1a18e9d6',
    'container.build_time' => 1770882203,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVFFsevy');
